server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account/**
          filters:
            - Authentication

        - id: transfer-service
          uri: lb://TRANSFER-SERVICE
          predicates:
            - Path=/transfer/**
          filters:
            - Authentication

        - id: people-service
          uri: lb://PEOPLE-SERVICE
          predicates:
            - Path=/people/**,/users/**
          filters:
            - Authentication


        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**,/admins/**,/managers/**,/users/**
          filters:
            - Authentication


#    globalcors:
#      cors-configurations:
#        '[/**]':
#          allowed-origins: "http://localhost:3000"
#          allowed-methods: "*"
#          allowed-headers: "*"
#          allow-credentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    kafka.system.api_gateway_forBank: DEBUG
    kafka.system.api_gateway_forBank.security.JwtAuthGlobalFilter: TRACE
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive: DEBUG