
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/microservice-AuthService
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

#### Producer Configuration
spring.kafka.producer.bootstrap-servers=localhost:9092,localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all

spring.kafka.producer.properties.delivery.timeout.ms=30000
spring.kafka.producer.properties.linger.ms=5000
spring.kafka.producer.properties.request.timeout.ms=5000
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5

spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.transaction-id-prefix=auth-service-${random.value}-
####

### Topics
create-admin-events-topic=create-admin-events-topic
create-manager-events-topic=create-manager-events-topic
create-user-events-topic=create-user-events-topic
create-default-account-event-topic=create-default-account-event-topic
###

### LOGGING
#logging.level.org.apache.kafka=DEBUG
#logging.level.org.springframework.kafka=DEBUG
#logging.level.kafka.system.AccountService.handle.TransferServiceEventHandler=TRACE
#
#logging.level.org.springframework.kafka.listener=TRACE
#logging.level.org.springframework.kafka.requestreply=TRACE
#
#logging.level.org.springframework.kafka.support.serializer=DEBUG
#logging.level.org.apache.kafka.common.serialization=DEBUG
###


